### ISSUE TITLE
Documentation > Utility > Visibility > Specific Screen Size: 'm--hidden'

### ISSUE THREAD

**Issue by IngridJac** [yoshino-digital/yoi#15]
In that case, showing the element only on small screens would require only 'm--hidden' utility. I would say that 'l--hidden' and 'xl--hidden' are not necessary.

![screenshot](https://user-images.githubusercontent.com/17355181/38367788-eb762770-38e3-11e8-8c2c-6087c91d3ef2.png)

**Comment by reimar** [comment]
You are totally right. I left the whole section out, did not make much sense anyways. The update doc page: https://yoshino-digital.github.io/yoi/utilities/visibility.html
