### ISSUE TITLE
Documentation > Visibility > 'vis-vis' and 'vis-hid'

### ISSUE THREAD

**Issue by IngridJac** [yoshino-digital/yoi#16]
I was wondering why **'.vis-vis'** and **'.vis-hid'** are not **'.vis-visible'** and **'.vis-hidden'** 
Values aren't not supposed to be not shortened? I am aware that it concerns **most** of them and not **all** of them :-)

![screenshot-vis](https://user-images.githubusercontent.com/17355181/38370294-13fdc03a-38ea-11e8-9263-64020071f7b4.png)

**Comment by reimar** [comment]
It should be fixed now. It was a combination of:

* the document page was outdated, the class names already changed
* I forgot to finish visibility-responsive.less

```
¯\_(ツ)_/¯
```
